### PR TITLE
adding another of the tidied html files

### PR DESCRIPTION
**Pull request by James-Is-A-Name**

### CODE REVIEW

**Review by catherineedwards — COMMENTED** [review]
Hey @James-Is-A-Name , nice work!! Your code is really tidy to look at. The only suggestions I would make would be to remove the following empty lines: 14, 54 and 144.

**Comment by James-Is-A-Name** [comment]
I do have a bad habit of leaving unneeded empty lines in.

**Review by catherineedwards — APPROVED** [review]
Nice, looking great!!

**Comment by catherineedwards** [comment]
Thank you @James-Is-A-Name !!

**Pull request merged**
